export const GET_POTENTIAL_MATCHES = "GET_POTENTIAL_MATCHES";
export const GET_USER = "GET_USER";
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const GET_USER_DETAILS = "GET_USER_DETAILS";

//like action types
export const SWIPE_RIGHT = "SWIPE_RIGHT";
export const SWIPE_LEFT = "SWIPE_LEFT";

//form action types
export const ADD_USER_APPEARANCE = "ADD_USER_APPEARANCE";
export const ADD_USER_DETAILS_INTERESTS = "ADD_USER_DETAILS_INTERESTS";
export const ADD_USER_PREF = "ADD_USER_PREF";
export const EDIT_USER_APPEARANCE = "EDIT_USER_APPEARANCE";
export const EDIT_USER_DETAILS = "EDIT_USER_DETAILS";
export const EDIT_USER_INTERESTS = "EDIT_USER_INTERESTS";
export const EDIT_USER_DETAILS_INTERESTS = "EDIT_USER_DETAILS_INTERESTS";
export const EDIT_USER_PREF = "EDIT_USER_PREF";
export const GET_USER_APPEARANCE = "GET_USER_APPEARANCE";
export const GET_USER_DETAILS_INTERESTS = "GET_USER_DETAILS_INTERESTS";
export const GET_USER_PREF = "GET_USER_PREF";
